/*
 * SERVICOS DE MANUTENCAO
 */
package manutencao.view;

import javax.swing.DefaultListModel;
import manutencao.controller.Controlador;
import manutencao.model.Pessoa;
import manutencao.model.Empresa;
import javax.swing.JOptionPane;
/**
 *
 * @author danie_000
 */
public class ClientesPanel extends javax.swing.JPanel
{
    private Controlador control;
    
    DefaultListModel listModel = new DefaultListModel();
   
    public void attLista()
    {
        listModel.clear();
        
        for(int i = 0; i < control.getClientesp().size(); i++) 
        {
            listModel.addElement(control.getClientesp().get(i).getNome());
        }
        
        for(int i = 0; i < control.getClientese().size(); i++) 
        {
            listModel.addElement(control.getClientese().get(i).getNome());
        }
    }
    /*public void attListae()
    {
        listModel.clear();
        
        for(int i = 0; i < control.getClientese().size(); i++) 
        {
            listModel.addElement(control.getClientese().get(i).getNome());
        }
    }*/
    
    
    /**
     * Creates new form FuncionariosPanel
     * @param c
     */
    public ClientesPanel(Controlador c)
    {
        this.control = c;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        TextoTelefone = new javax.swing.JTextField();
        TextoCpf = new javax.swing.JTextField();
        NomeLabel = new javax.swing.JLabel();
        TextoNome = new javax.swing.JTextField();
        TextoEndereco = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        BotaoCadastrar = new javax.swing.JButton();
        ScrollPanelClientesp = new javax.swing.JScrollPane();
        ListaClientesp = new javax.swing.JList<>();
        EnderecoLabel = new javax.swing.JLabel();
        TelefoneLabel = new javax.swing.JLabel();
        BotaoExcluir = new javax.swing.JButton();
        BotaoAlterar = new javax.swing.JButton();
        BotaoLimpar = new javax.swing.JButton();
        CpfLabel = new javax.swing.JLabel();
        TextoEmail = new javax.swing.JTextField();
        BotaoSalvar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        ScrollPanelClientesp1 = new javax.swing.JScrollPane();
        ListaClientespe = new javax.swing.JList<>();
        CpfLabele = new javax.swing.JLabel();
        TextoCnpj = new javax.swing.JTextField();
        NomeLabele = new javax.swing.JLabel();
        TextoNomee = new javax.swing.JTextField();
        EnderecoLabele = new javax.swing.JLabel();
        TextoEnderecoe = new javax.swing.JTextField();
        TelefoneLabele = new javax.swing.JLabel();
        EmailLabele = new javax.swing.JLabel();
        TextoTelefonee = new javax.swing.JTextField();
        TextoEmaile = new javax.swing.JTextField();
        ContatoLabele = new javax.swing.JLabel();
        TextoContato = new javax.swing.JTextField();
        BotaoCadastrare = new javax.swing.JButton();
        BotaoLimpare = new javax.swing.JButton();
        BotaoExcluire = new javax.swing.JButton();
        BotaoSalvare = new javax.swing.JButton();
        BotaoAlterare = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(0, 0));

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(400, 300));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(0, 0));

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));

        TextoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCpfActionPerformed(evt);
            }
        });

        NomeLabel.setText("Nome:");

        EmailLabel.setText("Email:");

        BotaoCadastrar.setText("Cadastrar");
        BotaoCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarActionPerformed(evt);
            }
        });

        ListaClientesp.setModel(listModel);
        ListaClientesp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ListaClientespFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ListaClientespFocusLost(evt);
            }
        });
        ListaClientesp.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ListaClientespComponentShown(evt);
            }
        });
        ScrollPanelClientesp.setViewportView(ListaClientesp);

        EnderecoLabel.setText("Endereço:");

        TelefoneLabel.setText("Telefone:");

        BotaoExcluir.setText("Excluir");
        BotaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirActionPerformed(evt);
            }
        });

        BotaoAlterar.setText("Alterar");
        BotaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAlterarActionPerformed(evt);
            }
        });

        BotaoLimpar.setText("Limpar");
        BotaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparActionPerformed(evt);
            }
        });

        CpfLabel.setText("Cpf:");

        BotaoSalvar.setText("Salvar");
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });

        jTextField1.setText("                                                                  Lista de Clientes");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BotaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(BotaoAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(BotaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ScrollPanelClientesp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CpfLabel)
                                    .addComponent(NomeLabel)
                                    .addComponent(EnderecoLabel)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(EmailLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TelefoneLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TextoTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                                    .addComponent(TextoEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextoNome, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextoCpf, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextoEmail)))
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPanelClientesp, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CpfLabel)
                    .addComponent(TextoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeLabel)
                    .addComponent(TextoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnderecoLabel)
                    .addComponent(TextoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefoneLabel)
                    .addComponent(TextoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLabel)
                    .addComponent(TextoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(BotaoLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoCadastrar)
                    .addComponent(BotaoExcluir)
                    .addComponent(BotaoSalvar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cliente Pessoa", jPanel1);

        ListaClientespe.setModel(listModel);
        ListaClientespe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ListaClientespeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ListaClientespeFocusLost(evt);
            }
        });
        ListaClientespe.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ListaClientespeComponentShown(evt);
            }
        });
        ScrollPanelClientesp1.setViewportView(ListaClientespe);

        CpfLabele.setText("CNPJ:");

        TextoCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCnpjActionPerformed(evt);
            }
        });

        NomeLabele.setText("Nome:");

        EnderecoLabele.setText("Endereço:");

        TelefoneLabele.setText("Telefone:");

        EmailLabele.setText("Email:");

        ContatoLabele.setText("Contato:");

        BotaoCadastrare.setText("Cadastrar");
        BotaoCadastrare.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoCadastrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrareActionPerformed(evt);
            }
        });

        BotaoLimpare.setText("Limpar");
        BotaoLimpare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimpareActionPerformed(evt);
            }
        });

        BotaoExcluire.setText("Excluir");
        BotaoExcluire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluireActionPerformed(evt);
            }
        });

        BotaoSalvare.setText("Salvar");
        BotaoSalvare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvareActionPerformed(evt);
            }
        });

        BotaoAlterare.setText("Alterar");
        BotaoAlterare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAlterareActionPerformed(evt);
            }
        });

        jTextField2.setText("                                                                  Lista de Clientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPanelClientesp1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BotaoCadastrare, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoAlterare)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoSalvare)
                        .addGap(31, 31, 31)
                        .addComponent(BotaoLimpare, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoExcluire, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CpfLabele)
                            .addComponent(NomeLabele)
                            .addComponent(EnderecoLabele)
                            .addComponent(TelefoneLabele)
                            .addComponent(EmailLabele)
                            .addComponent(ContatoLabele, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextoContato)
                            .addComponent(TextoTelefonee)
                            .addComponent(TextoEnderecoe)
                            .addComponent(TextoNomee)
                            .addComponent(TextoCnpj, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextoEmaile))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(ScrollPanelClientesp1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CpfLabele))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextoNomee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeLabele))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnderecoLabele)
                    .addComponent(TextoEnderecoe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TelefoneLabele)
                    .addComponent(TextoTelefonee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmailLabele)
                    .addComponent(TextoEmaile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContatoLabele, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCadastrare)
                    .addComponent(BotaoAlterare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoSalvare)
                    .addComponent(BotaoLimpare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoExcluire))
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("Cliente Empresa", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoCpfActionPerformed

    private void BotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarActionPerformed
        if((!"".equals(TextoCpf.getText()))&&(!"".equals(TextoEmail.getText()))&&(!"".equals(TextoNome.getText()))&&(!"".equals(TextoEndereco.getText()))&&(!"".equals(TextoTelefone.getText())))
        {
            if(control.CadastrarPessoa(TextoCpf.getText( ),TextoEmail.getText(),TextoNome.getText(),TextoEndereco.getText(),TextoTelefone.getText()))
            {
                attLista();
                JOptionPane.showMessageDialog(null,"Cadastrado com Sucesso!");              
            }

            else
            {
                System.out.println("Erro ao cadastrar");
                JOptionPane.showMessageDialog(null,"Ja existe Cliente com esse CPF");
            }  
        }
        else
            JOptionPane.showMessageDialog(null,"Não foi possivel Cadastar, pois há campos vazios!");
        TextoCpf.setText("");
        TextoEmail.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");
    }//GEN-LAST:event_BotaoCadastrarActionPerformed

    private void ListaClientespFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ListaClientespFocusGained
        /*if(control.getFuncionarios()!=null)
        {
            TextoMatricula.setText(control.getFuncionarios().get(0).getMatricula());
            //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
            TextoNome.setText(control.getFuncionarios().get(0).getNome());
            TextoEndereco.setText(control.getFuncionarios().get(0).getEndereco());
            TextoTelefone.setText(control.getFuncionarios().get(0).getTelefone());
        }*/
    }//GEN-LAST:event_ListaClientespFocusGained

    private void ListaClientespFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ListaClientespFocusLost
        /*TextoMatricula.setText("");
        TextoSalario.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");*/
    }//GEN-LAST:event_ListaClientespFocusLost

    private void ListaClientespComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ListaClientespComponentShown
        /*TextoMatricula.setText(control.getFuncionarios().get(1).getMatricula());
        //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
        TextoNome.setText(control.getFuncionarios().get(1).getNome());
        TextoEndereco.setText(control.getFuncionarios().get(1).getEndereco());
        TextoTelefone.setText(control.getFuncionarios().get(1).getTelefone());*/
    }//GEN-LAST:event_ListaClientespComponentShown

    private void BotaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirActionPerformed
        // TODO add your handling code here:
        if(control.BuscaCPF(TextoCpf.getText()))
        {
           control.ExcluirPessoa(control.getClienteP(TextoCpf.getText()));
           listModel.removeElement(control.getNomeClienteP((TextoCpf.getText()))); 
           attLista();
           JOptionPane.showMessageDialog(null,"Excluido com Sucesso!");
        }
        else
        {
           JOptionPane.showMessageDialog(null,"Não existe Cliente com esse CPF");
        }
        TextoCpf.setText("");
    }//GEN-LAST:event_BotaoExcluirActionPerformed

    private void BotaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimparActionPerformed
        TextoCpf.setText("");
        TextoEmail.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");
        TextoCpf.setEnabled(true);
        TextoNome.setEnabled(true);
    }//GEN-LAST:event_BotaoLimparActionPerformed

    private void ListaClientespeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ListaClientespeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaClientespeFocusGained

    private void ListaClientespeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ListaClientespeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaClientespeFocusLost

    private void ListaClientespeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ListaClientespeComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaClientespeComponentShown

    private void TextoCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoCnpjActionPerformed

    private void BotaoCadastrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrareActionPerformed
        // TODO add your handling code here:
        if((!"".equals(TextoCnpj.getText()))&&(!"".equals(TextoEmaile.getText()))&&(!"".equals(TextoNomee.getText()))&&(!"".equals(TextoEnderecoe.getText()))&&(!"".equals(TextoTelefonee.getText()))&&(!"".equals(TextoContato.getText())))
        {
            if(control.CadastrarEmpresa(TextoCnpj.getText( ),TextoContato.getText(),TextoEmaile.getText(),TextoNomee.getText(),TextoEnderecoe.getText(),TextoTelefonee.getText()))
            {
                attLista();
                JOptionPane.showMessageDialog(null,"Cadastrado com Sucesso!");
            }

            else
            {
                System.out.println("Erro ao cadastrar");
                JOptionPane.showMessageDialog(null,"Ja existe Cliente com esse CNPJ");
            }
        }
        else
           JOptionPane.showMessageDialog(null,"Não foi possivel Cadastrar, pois ha campos vazios!"); 
        TextoCnpj.setText("");
        TextoEmaile.setText("");
        TextoNomee.setText("");
        TextoEnderecoe.setText("");
        TextoTelefonee.setText("");
        TextoContato.setText("");
    }//GEN-LAST:event_BotaoCadastrareActionPerformed

    private void BotaoLimpareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimpareActionPerformed
        // TODO add your handling code here:
        TextoCnpj.setText("");
        TextoEmaile.setText("");
        TextoNomee.setText("");
        TextoEnderecoe.setText("");
        TextoTelefonee.setText("");
        TextoContato.setText("");
        TextoCnpj.setEnabled(true);
        TextoNomee.setEnabled(true);
    }//GEN-LAST:event_BotaoLimpareActionPerformed

    private void BotaoExcluireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluireActionPerformed
        // TODO add your handling code here:
        if(control.BuscaCNPJ(TextoCnpj.getText()))
        {
            control.ExcluirEmpresa(control.getClienteE(TextoCnpj.getText()));
            listModel.removeElement(control.getNomeClienteE((TextoCnpj.getText())));
            attLista();
            JOptionPane.showMessageDialog(null,"Excluido com Sucesso!");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Não existe Cliente com esse CNPJ");
        }
        TextoCnpj.setText("");
    }//GEN-LAST:event_BotaoExcluireActionPerformed

    private void BotaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAlterarActionPerformed
        // TODO add your handling code here:
        if(control.BuscaCPF(TextoCpf.getText()))
        {
            TextoCpf.setEnabled(false);
            TextoNome.setEnabled(false);
            TextoNome.setText(control.getNomeClienteP(TextoCpf.getText()));
            TextoEndereco.setText(control.getEndClienteP(TextoCpf.getText()));
            TextoTelefone.setText(control.getTelClienteP(TextoCpf.getText()));
            TextoEmail.setText(control.getEmailClienteP(TextoCpf.getText()));      
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Não existe Cliente com esse CPF");
        }
    }//GEN-LAST:event_BotaoAlterarActionPerformed

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed
        // TODO add your handling code here:
        TextoCpf.setEnabled(true);
        TextoNome.setEnabled(true);
        if((!"".equals(TextoCpf.getText()))&&(!"".equals(TextoEmail.getText()))&&(!"".equals(TextoNome.getText()))&&(!"".equals(TextoEndereco.getText()))&&(!"".equals(TextoTelefone.getText())))
        {
            control.AlterarPessoa(control.getClienteP(TextoCpf.getText()),TextoEmail.getText(),TextoEndereco.getText(),TextoTelefone.getText());
            JOptionPane.showMessageDialog(null,"Alterado com Sucesso!");
        }
        else
            JOptionPane.showMessageDialog(null,"Não foi possivel alterar pois há campos vazios!");
                            
        
        
        TextoCpf.setText("");
        TextoEmail.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    private void BotaoSalvareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvareActionPerformed
        // TODO add your handling code here:
        TextoCnpj.setEnabled(true);
        TextoNomee.setEnabled(true);
        
        if((!"".equals(TextoCnpj.getText()))&&(!"".equals(TextoEmaile.getText()))&&(!"".equals(TextoNomee.getText()))&&(!"".equals(TextoEnderecoe.getText()))&&(!"".equals(TextoTelefonee.getText()))&&(!"".equals(TextoContato.getText())))
        {
            control.AlterarEmpresa(control.getClienteE(TextoCnpj.getText()),TextoContato.getText(),TextoEmaile.getText(),TextoEnderecoe.getText(),TextoTelefonee.getText());                                 
            JOptionPane.showMessageDialog(null,"Alterado com Sucesso!");
        }
        else
            JOptionPane.showMessageDialog(null,"Não foi possivel alterar pois há campos vazios!");
        
        TextoCnpj.setText("");
        TextoEmaile.setText("");
        TextoNomee.setText("");
        TextoEnderecoe.setText("");
        TextoTelefonee.setText("");
        TextoContato.setText("");
    }//GEN-LAST:event_BotaoSalvareActionPerformed

    private void BotaoAlterareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAlterareActionPerformed
        // TODO add your handling code here:
        if(control.BuscaCNPJ(TextoCnpj.getText()))
        {
            TextoCnpj.setEnabled(false);
            TextoNomee.setEnabled(false);
            TextoNomee.setText(control.getNomeClienteE(TextoCnpj.getText()));
            TextoEnderecoe.setText(control.getEndClienteE(TextoCnpj.getText()));
            TextoTelefonee.setText(control.getTelClienteE(TextoCnpj.getText()));
            TextoEmaile.setText(control.getEmailClienteE(TextoCnpj.getText()));  
            TextoContato.setText(control.getEmailClienteE(TextoCnpj.getText()));
        } 
        else
        {
            JOptionPane.showMessageDialog(null,"Não existe Cliente com esse CNPJ"); 
        }
    }//GEN-LAST:event_BotaoAlterareActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAlterar;
    private javax.swing.JButton BotaoAlterare;
    private javax.swing.JButton BotaoCadastrar;
    private javax.swing.JButton BotaoCadastrare;
    private javax.swing.JButton BotaoExcluir;
    private javax.swing.JButton BotaoExcluire;
    private javax.swing.JButton BotaoLimpar;
    private javax.swing.JButton BotaoLimpare;
    private javax.swing.JButton BotaoSalvar;
    private javax.swing.JButton BotaoSalvare;
    private javax.swing.JLabel ContatoLabele;
    private javax.swing.JLabel CpfLabel;
    private javax.swing.JLabel CpfLabele;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel EmailLabele;
    private javax.swing.JLabel EnderecoLabel;
    private javax.swing.JLabel EnderecoLabele;
    private javax.swing.JList<Pessoa> ListaClientesp;
    private javax.swing.JList<Pessoa> ListaClientespe;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JLabel NomeLabele;
    private javax.swing.JScrollPane ScrollPanelClientesp;
    private javax.swing.JScrollPane ScrollPanelClientesp1;
    private javax.swing.JLabel TelefoneLabel;
    private javax.swing.JLabel TelefoneLabele;
    private javax.swing.JTextField TextoCnpj;
    private javax.swing.JTextField TextoContato;
    private javax.swing.JTextField TextoCpf;
    private javax.swing.JTextField TextoEmail;
    private javax.swing.JTextField TextoEmaile;
    private javax.swing.JTextField TextoEndereco;
    private javax.swing.JTextField TextoEnderecoe;
    private javax.swing.JTextField TextoNome;
    private javax.swing.JTextField TextoNomee;
    private javax.swing.JTextField TextoTelefone;
    private javax.swing.JTextField TextoTelefonee;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void setResizable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
