/*
 * SERVICOS DE MANUTENCAO
 */
package manutencao.view;

import manutencao.controller.Controlador;
/*
 * @author danie_000
 */
public class Janela extends javax.swing.JFrame
{
        
    ////////////////////////////////////////////////////////////////////////////    
    ////////////////////////////////////////////////////////////////////////////
    
    public Janela()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        AltMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UFF Manutenções 2018");
        setMinimumSize(new java.awt.Dimension(410, 330));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout());

        AltMenu.setName("AltMenu"); // NOI18N

        jMenu1.setText("File");
        AltMenu.add(jMenu1);

        jMenu2.setText("Edit");
        AltMenu.add(jMenu2);

        setJMenuBar(AltMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    ////////////////////////////////////////////////////////////////////////////    
    ////////////////////////////////////////////////////////////////////////////
                                                        ////////////////////////
    /**                                                 ////////////////////////
     * @param args the command line arguments           ////////////////////////
     */                                                 ////////////////////////
    public static void main(String args[])              ////////////////////////
    {                                                   ////////////////////////
        Controlador control = new Controlador();        ////////////////////////
        //FuncionariosPanel fpanel = new FuncionariosPanel(control);
        PecasPanel ppanel = new PecasPanel(control);
        PrincipalPanel mainpanel = new PrincipalPanel();////////////////////////
                                                        ////////////////////////
    ////////////////////////////////////////////////////////////////////////////    
    ////////////////////////////////////////////////////////////////////////////
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {    
                //control.CadastrarFuncionario("1",3.12f,"Eduardo","Itaperuna","997537676");
                
                //fpanel.attLista();
                ppanel.attLista();
                
                Janela janela = new Janela();
                
                //janela.setContentPane(fpanel);
                janela.setContentPane(ppanel);
                
                janela.setVisible(true);

                
            }
        });
    }

    ////////////////////////////////////////////////////////////////////////////    
    ////////////////////////////////////////////////////////////////////////////
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar AltMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    // End of variables declaration//GEN-END:variables
}
