/*
 * SERVICOS DE MANUTENCAO
 */
package manutencao.view;

//import javax.swing.DefaultButtonModel
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import manutencao.controller.Controlador;
import manutencao.model.Peca;

/**
 *
 * @author nayara
 */
public class PecasPanel extends javax.swing.JPanel {
    
    private Controlador control;
    
    DefaultListModel listModel = new DefaultListModel();
            
    public void attLista() {
        /*listModel.clear();
                       
        for(int i = 0; i < control.getPeca().size(); i++) 
        {
            //listModel.addElement(control.getPeca().get(i).getCodigo());
            //listModel.addElement(control.getPeca().get(i).getNome());
            //listModel.addElement(control.getPeca().get(i).getPreco());
            //listModel.addElement(control.getPeca().get(i).getValor());
        }*/
        
    }
     /**
     * Creates new form PecasPanel
     * @param c
     */
    public PecasPanel(Controlador c) {        
        this.control = c;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoCadastrar = new javax.swing.JButton();
        CodigoLabel = new javax.swing.JLabel();
        TextoCodigo = new javax.swing.JTextField();
        NomeLabel = new javax.swing.JLabel();
        TextoNome = new javax.swing.JTextField();
        PrecoLabel = new javax.swing.JLabel();
        TextoPreco = new javax.swing.JTextField();
        ValorLabel = new javax.swing.JLabel();
        TextoValor = new javax.swing.JTextField();
        BotaoAlterar = new javax.swing.JButton();
        BotaoLimpar = new javax.swing.JButton();
        BotaoExcluir = new javax.swing.JButton();
        ScrollPanelPecas = new javax.swing.JScrollPane();
        ListaPeca = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaPeca = new javax.swing.JTable();

        BotaoCadastrar.setText("Cadastrar");
        BotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarActionPerformed(evt);
            }
        });

        CodigoLabel.setText("Código: ");

        NomeLabel.setText("Nome: ");

        PrecoLabel.setText("Preço R$: ");

        ValorLabel.setText("Valor R$: ");

        BotaoAlterar.setText("Alterar");
        BotaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAlterarActionPerformed(evt);
            }
        });

        BotaoLimpar.setText("Limpar");
        BotaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparActionPerformed(evt);
            }
        });

        BotaoExcluir.setText("Excluir");
        BotaoExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoExcluirMouseClicked(evt);
            }
        });

        ListaPeca.setModel(listModel);
        ListaPeca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ListaPecaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ListaPecaFocusLost(evt);
            }
        });
        ListaPeca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaPecaMouseClicked(evt);
            }
        });
        ListaPeca.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ListaPecaComponentShown(evt);
            }
        });
        ScrollPanelPecas.setViewportView(ListaPeca);

        TabelaPeca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Preco", "Valor"
            }
        ));
        TabelaPeca.setColumnSelectionAllowed(false);
        TabelaPeca.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                TabelaPecaComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaPeca);
        TabelaPeca.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (TabelaPeca.getColumnModel().getColumnCount() > 0) {
            TabelaPeca.getColumnModel().getColumn(0).setHeaderValue("Codigo");
            TabelaPeca.getColumnModel().getColumn(1).setHeaderValue("Nome");
            TabelaPeca.getColumnModel().getColumn(2).setHeaderValue("Preco");
            TabelaPeca.getColumnModel().getColumn(3).setHeaderValue("Valor");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CodigoLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ScrollPanelPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(NomeLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TextoNome))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PrecoLabel)
                                        .addComponent(ValorLabel))
                                    .addGap(10, 10, 10)
                                    .addComponent(TextoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TextoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BotaoCadastrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BotaoAlterar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BotaoLimpar)
                            .addGap(10, 10, 10)
                            .addComponent(BotaoExcluir)))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BotaoAlterar, BotaoCadastrar, BotaoExcluir, BotaoLimpar});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CodigoLabel, NomeLabel, PrecoLabel, ValorLabel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ScrollPanelPecas, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoLabel)
                    .addComponent(TextoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeLabel)
                    .addComponent(TextoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PrecoLabel)
                    .addComponent(TextoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValorLabel)
                    .addComponent(TextoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCadastrar)
                    .addComponent(BotaoAlterar)
                    .addComponent(BotaoLimpar)
                    .addComponent(BotaoExcluir))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BotaoAlterar, BotaoCadastrar, BotaoExcluir, BotaoLimpar});

    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarActionPerformed
        
        DefaultTableModel tableModel = (DefaultTableModel) TabelaPeca.getModel();
        
        if((!"".equals(TextoCodigo.getText()))&&(!"".equals(TextoNome.getText()))&&(!"".equals(TextoPreco.getText()))&&(!"".equals(TextoValor.getText())))
        {
            if(control.CadastrarPeca(TextoCodigo.getText().trim(),TextoNome.getText().trim(),Float.parseFloat(TextoPreco.getText().trim()),Float.parseFloat(TextoValor.getText().trim())))
            {
                //attLista();
                tableModel.addRow(new Object[]{TextoCodigo.getText().trim(),TextoNome.getText().trim(),Float.parseFloat(TextoPreco.getText().trim()),Float.parseFloat(TextoValor.getText().trim())});
            }
            
            else
            
            {
                //System.out.println("Erro ao cadastrar peca");
                JOptionPane.showMessageDialog(null,"Erro ao cadastrar");
            }
        }
        else 
            JOptionPane.showMessageDialog(null,"Preencha os campos");
    }//GEN-LAST:event_BotaoCadastrarActionPerformed

    private void ListaPecaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ListaPecaComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaPecaComponentShown

    private void ListaPecaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ListaPecaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaPecaFocusGained

    private void ListaPecaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ListaPecaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaPecaFocusLost

    private void BotaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimparActionPerformed
        //limpa todos os campos não caso nada tenha sido selecionado 
        if (TextoCodigo.getSelectedText()== null && TextoNome.getSelectedText() == null && TextoPreco.getSelectedText() == null && TextoValor.getSelectedText() == null){
            TextoCodigo.setText("");
            TextoNome.setText("");
            TextoPreco.setText("");
            TextoValor.setText("");
        }//limpa campo selecionado 
        else if (TextoCodigo.getText() == null ? TextoCodigo.getSelectedText() == null : TextoCodigo.getText().equals(TextoCodigo.getSelectedText()))
            TextoCodigo.setText("");
        else if (TextoNome.getText() == null ? TextoNome.getSelectedText() == null : TextoNome.getText().equals(TextoNome.getSelectedText()))
            TextoNome.setText("");
        else if (TextoPreco.getText() == null ? TextoPreco.getSelectedText() == null : TextoPreco.getText().equals(TextoPreco.getSelectedText()))
            TextoPreco.setText("");
        else if (TextoValor.getText() == null ? TextoValor.getSelectedText() == null : TextoValor.getText().equals(TextoValor.getSelectedText()))    
            TextoValor.setText("");
    }//GEN-LAST:event_BotaoLimparActionPerformed
    
    private void excluirCadastrado(){
        //int pos = ListaPeca.getSelectedIndex();
        int pos = TabelaPeca.getSelectedRow();
        
        if (pos == -1){
            //System.out.println("Selecione para excluir");
            JOptionPane.showMessageDialog(null,"Selecione para excluir");
        }
        else {
            
            DefaultTableModel tableModel = (DefaultTableModel) TabelaPeca.getModel();
            //control.getPeca().remove(pos);
            tableModel.removeRow(pos);
            //attLista();
        }
    }
    
    private void BotaoExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoExcluirMouseClicked
        // ao clicar o botão excluir remove ou não o elemento da posição capturada 
        
        //if (ListaPeca.getFirstVisibleIndex() == -1)
        if (TabelaPeca.getRowCount() == 0)
            //mensagem para quando a lista estiver vazia
            JOptionPane.showMessageDialog(null,"Nenumha peça cadastrada");
        else 
            excluirCadastrado();
    }//GEN-LAST:event_BotaoExcluirMouseClicked

    private void ListaPecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaPecaMouseClicked
        //Não faz nada 
        //Peca selectPeca;
        //selectPeca = (Peca)ListaPeca.getSelectedValue();
        /*int pos = ListaPeca.getSelectedIndex();
        if(pos == -1){
            System.out.println("Estou aqui ");
        }
        else if(MouseEvent.BUTTON1 == evt.getButton()){
                System.out.println("Estou aqui 56 "+pos);
        }*/                
    }//GEN-LAST:event_ListaPecaMouseClicked
    
    private void alterarCadastrado(){
        //int pos = ListaPeca.getSelectedIndex();
        int pos = TabelaPeca.getSelectedRow();
        
        if (pos == -1){
            //System.out.println("Selecione peca para alterar");
            JOptionPane.showMessageDialog(null,"Selecione a peca que deseja alterar");
        }
        else {
            //altera o valor da primeira posição, mas ta dando problema se não for a primeira posição
            //control.getPeca().get(pos).setValor(Float.parseFloat(TextoValor.getText()));
            TabelaPeca.setValueAt(Float.parseFloat(TextoValor.getText()), pos, 3);
            //attLista();
        }
    }
    
    private void BotaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAlterarActionPerformed
        //if (ListaPeca.getFirstVisibleIndex() == -1)
        if (TabelaPeca.getRowCount() == 0)
            //mensagem para quando a lista estiver vazia
            JOptionPane.showMessageDialog(null,"Nenumha peça cadastrada");             
        else 
            alterarCadastrado();
    }//GEN-LAST:event_BotaoAlterarActionPerformed

    private void TabelaPecaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TabelaPecaComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelaPecaComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAlterar;
    private javax.swing.JButton BotaoCadastrar;
    private javax.swing.JButton BotaoExcluir;
    private javax.swing.JButton BotaoLimpar;
    private javax.swing.JLabel CodigoLabel;
    private javax.swing.JList<Peca> ListaPeca;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JLabel PrecoLabel;
    private javax.swing.JScrollPane ScrollPanelPecas;
    private javax.swing.JTable TabelaPeca;
    private javax.swing.JTextField TextoCodigo;
    private javax.swing.JTextField TextoNome;
    private javax.swing.JTextField TextoPreco;
    private javax.swing.JTextField TextoValor;
    private javax.swing.JLabel ValorLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
