/*
 * SERVICOS DE MANUTENCAO
 */
package manutencao.view;

//import javax.swing.DefaultButtonModel
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import manutencao.controller.Controlador;
import manutencao.model.Peca;

/**
 *
 * @author nayara
 */
public class PecasPanel extends javax.swing.JPanel {
    
    private Controlador control;
    
    DefaultListModel listModel = new DefaultListModel();
   
    public void attLista()
    {
        listModel.clear();
        
        for(int i = 0; i < control.getPecas().size(); i++) 
        {
            listModel.addElement(control.getPecas().get(i).getNome());
        }
        
    }
     /**
     * Creates new form PecasPanel
     * @param c
     */
    public PecasPanel(Controlador c) {        
        this.control = c;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        BotaoCadastrar = new javax.swing.JButton();
        BotaoAlterar = new javax.swing.JButton();
        BotaoSalvar = new javax.swing.JButton();
        BotaoLimpar = new javax.swing.JButton();
        BotaoExcluir = new javax.swing.JButton();
        ScrollPanelClientesp = new javax.swing.JScrollPane();
        ListaPeças = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoCodigo = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextoNome = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextoPreço = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextoValor = new javax.swing.JTextPane();

        jTabbedPane1.setMinimumSize(new java.awt.Dimension(400, 300));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(0, 0));

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));

        BotaoCadastrar.setText("Cadastrar");
        BotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarActionPerformed(evt);
            }
        });

        BotaoAlterar.setText("Alterar");
        BotaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAlterarActionPerformed(evt);
            }
        });

        BotaoSalvar.setText("Salvar");
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });

        BotaoLimpar.setText("Limpar");
        BotaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparActionPerformed(evt);
            }
        });

        BotaoExcluir.setText("Excluir");
        BotaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirActionPerformed(evt);
            }
        });

        ListaPeças.setModel(listModel);
        ListaPeças.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ListaPeçasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ListaPeçasFocusLost(evt);
            }
        });
        ListaPeças.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ListaPeçasComponentShown(evt);
            }
        });
        ScrollPanelClientesp.setViewportView(ListaPeças);

        jTextField1.setText("                                                                  Lista de Peças");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo:");

        jScrollPane1.setViewportView(TextoCodigo);

        jLabel2.setText("Nome:");

        jScrollPane2.setViewportView(TextoNome);

        jLabel3.setText("Preço:");

        jScrollPane3.setViewportView(TextoPreço);

        jLabel4.setText("Valor:");

        jScrollPane4.setViewportView(TextoValor);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BotaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoAlterar)
                        .addGap(5, 5, 5)
                        .addComponent(BotaoSalvar)
                        .addGap(38, 38, 38)
                        .addComponent(BotaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ScrollPanelClientesp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4)
                                .addComponent(jScrollPane3)
                                .addComponent(jScrollPane2)
                                .addComponent(jScrollPane1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPanelClientesp, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCadastrar)
                    .addComponent(BotaoAlterar)
                    .addComponent(BotaoSalvar)
                    .addComponent(BotaoLimpar)
                    .addComponent(BotaoExcluir))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Peças", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoExcluirActionPerformed
        // TODO add your handling code here:
        if(control.BuscaCODIGO(TextoCodigo.getText()))
        {
            control.ExcluirPeca(control.getPeca(TextoCodigo.getText()));
            listModel.removeElement(control.getNomePecas((TextoCodigo.getText())));
            attLista();
            JOptionPane.showMessageDialog(null,"Excluido com Sucesso!");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Não existe Peças com esse CODIGO");
        }
        TextoCodigo.setText("");
    }//GEN-LAST:event_BotaoExcluirActionPerformed

    private void BotaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimparActionPerformed
        // TODO add your handling code here:
        TextoCodigo.setText("");
        TextoNome.setText("");
        TextoPreço.setText("");
        TextoValor.setText("");
    }//GEN-LAST:event_BotaoLimparActionPerformed

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed
        // TODO add your handling code here:
        TextoCodigo.setEnabled(true);
        TextoNome.setEnabled(true);
        if((!"".equals(TextoNome.getText()))&&(!"".equals(TextoCodigo.getText()))&&(!"".equals(TextoPreço.getText()))&&(!"".equals(TextoValor.getText())))
        {
            control.AlterarPeca(control.getPeca(TextoCodigo.getText()),Float.parseFloat(TextoValor.getText()));
            JOptionPane.showMessageDialog(null,"Alterado com Sucesso!");
        }
        else
        JOptionPane.showMessageDialog(null,"Não foi possivel alterar pois há campos vazios!");

        TextoCodigo.setText("");
        TextoNome.setText("");
        TextoPreço.setText("");
        TextoValor.setText("");
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    private void BotaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAlterarActionPerformed
        // TODO add your handling code here:
        if(control.BuscaCODIGO(TextoCodigo.getText()))
        {
            TextoCodigo.setEnabled(false);
            TextoNome.setEnabled(false);
            TextoNome.setText(control.getNomePecas(TextoCodigo.getText()));
            TextoPreço.setText(String.valueOf(control.getPrecoPecas(TextoCodigo.getText())));
            TextoValor.setText(String.valueOf(control.getValorPecas(TextoCodigo.getText())));
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Não existe Peças com esse CODIGO");
        }
    }//GEN-LAST:event_BotaoAlterarActionPerformed

    private void BotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarActionPerformed
        // TODO add your handling code here:
        if((!"".equals(TextoCodigo.getText()))&&(!"".equals(TextoNome.getText()))&&(!"".equals(TextoPreço.getText()))&&(!"".equals(TextoValor.getText())))
        {
            if(control.CadastrarPeca(TextoCodigo.getText( ),TextoNome.getText(),Float.parseFloat(TextoPreço.getText()),Float.parseFloat(TextoValor.getText())))
            {
                attLista();
                JOptionPane.showMessageDialog(null,"Cadastrado com Sucesso!");
            }
            else
            {
                System.out.println("Erro ao cadastrar");
                JOptionPane.showMessageDialog(null,"Ja existe Peça com esse CODIGO");
            }
        }
        else
        JOptionPane.showMessageDialog(null,"Não foi possivel Cadastar, pois há campos vazios!");

        TextoCodigo.setText("");
        TextoNome.setText("");
        TextoPreço.setText("");
        TextoValor.setText("");
    }//GEN-LAST:event_BotaoCadastrarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ListaPeçasComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ListaPeçasComponentShown
        /*TextoMatricula.setText(control.getFuncionarios().get(1).getMatricula());
        //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
        TextoNome.setText(control.getFuncionarios().get(1).getNome());
        TextoEndereco.setText(control.getFuncionarios().get(1).getEndereco());
        TextoTelefone.setText(control.getFuncionarios().get(1).getTelefone());*/
    }//GEN-LAST:event_ListaPeçasComponentShown

    private void ListaPeçasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ListaPeçasFocusLost
        /*TextoMatricula.setText("");
        TextoSalario.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");*/
    }//GEN-LAST:event_ListaPeçasFocusLost

    private void ListaPeçasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ListaPeçasFocusGained
        /*if(control.getFuncionarios()!=null)
        {
            TextoMatricula.setText(control.getFuncionarios().get(0).getMatricula());
            //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
            TextoNome.setText(control.getFuncionarios().get(0).getNome());
            TextoEndereco.setText(control.getFuncionarios().get(0).getEndereco());
            TextoTelefone.setText(control.getFuncionarios().get(0).getTelefone());
        }*/
    }//GEN-LAST:event_ListaPeçasFocusGained
    
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAlterar;
    private javax.swing.JButton BotaoCadastrar;
    private javax.swing.JButton BotaoExcluir;
    private javax.swing.JButton BotaoLimpar;
    private javax.swing.JButton BotaoSalvar;
    private javax.swing.JList<Peca> ListaPeças;
    private javax.swing.JScrollPane ScrollPanelClientesp;
    private javax.swing.JTextPane TextoCodigo;
    private javax.swing.JTextPane TextoNome;
    private javax.swing.JTextPane TextoPreço;
    private javax.swing.JTextPane TextoValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
